version: '3.2'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
    webserver:
        image: nginx:alpine
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    db:
        image: mysql:8.0
        ports:
            - "33061:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ./_docker/data/mysql:/var/lib/mysql
